"""initial schema: accounts/users, farm, reports, alerts, agent (BYOK, conversations, memory),
weather hypertables. Extensions: timescaledb + vector. Schema `adk` is left to Google ADK.

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 17:36:31.153470
"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GLOBAL_CROPS = [
    # name, variety, scientific_name, family, growth_period_days, planting_season, harvest_season
    ("Tomate", "Redondo", "Solanum lycopersicum", "Solanaceae", 120, "Sep-Nov (almácigo Jul-Ago)", "Dic-Mar"),
    ("Tomate", "Cherry", "Solanum lycopersicum var. cerasiforme", "Solanaceae", 100, "Sep-Nov", "Dic-Abr"),
    ("Pimiento", None, "Capsicum annuum", "Solanaceae", 130, "Oct-Nov (almácigo Jul-Ago)", "Ene-Abr"),
    ("Berenjena", None, "Solanum melongena", "Solanaceae", 130, "Oct-Nov", "Ene-Abr"),
    ("Papa", None, "Solanum tuberosum", "Solanaceae", 110, "Ago-Oct / Feb", "Dic-Ene / May-Jun"),
    ("Lechuga", "Mantecosa", "Lactuca sativa", "Asteraceae", 60, "Todo el año (evitar pleno verano)", "Todo el año"),
    ("Lechuga", "Crespa", "Lactuca sativa", "Asteraceae", 55, "Todo el año (evitar pleno verano)", "Todo el año"),
    ("Rúcula", None, "Eruca vesicaria", "Brassicaceae", 40, "Mar-Nov", "Abr-Dic"),
    ("Espinaca", None, "Spinacia oleracea", "Amaranthaceae", 50, "Feb-May / Ago-Sep", "Abr-Oct"),
    ("Acelga", None, "Beta vulgaris var. cicla", "Amaranthaceae", 60, "Feb-Abr / Ago-Oct", "Todo el año"),
    ("Remolacha", None, "Beta vulgaris", "Amaranthaceae", 80, "Ago-Mar", "Nov-Jun"),
    ("Zanahoria", None, "Daucus carota", "Apiaceae", 110, "Ago-Mar", "Nov-Jul"),
    ("Perejil", None, "Petroselinum crispum", "Apiaceae", 75, "Ago-Mar", "Todo el año"),
    ("Albahaca", None, "Ocimum basilicum", "Lamiaceae", 60, "Oct-Dic", "Dic-Abr"),
    ("Cebolla", None, "Allium cepa", "Amaryllidaceae", 180, "Mar-Jun (almácigo)", "Nov-Ene"),
    ("Ajo", None, "Allium sativum", "Amaryllidaceae", 210, "Mar-May", "Nov-Dic"),
    ("Puerro", None, "Allium porrum", "Amaryllidaceae", 150, "Ago-Nov", "Mar-Ago"),
    ("Zapallito", "Redondo de tronco", "Cucurbita maxima var. zapallito", "Cucurbitaceae", 60, "Oct-Ene", "Dic-Abr"),
    ("Zapallo", "Anco", "Cucurbita moschata", "Cucurbitaceae", 120, "Oct-Dic", "Feb-May"),
    ("Pepino", None, "Cucumis sativus", "Cucurbitaceae", 65, "Oct-Dic", "Dic-Mar"),
    ("Melón", None, "Cucumis melo", "Cucurbitaceae", 100, "Oct-Nov", "Ene-Mar"),
    ("Sandía", None, "Citrullus lanatus", "Cucurbitaceae", 100, "Oct-Nov", "Ene-Mar"),
    ("Chaucha", None, "Phaseolus vulgaris", "Fabaceae", 70, "Oct-Feb", "Dic-Abr"),
    ("Arveja", None, "Pisum sativum", "Fabaceae", 110, "Mar-Jun", "Ago-Nov"),
    ("Haba", None, "Vicia faba", "Fabaceae", 150, "Mar-May", "Sep-Nov"),
    ("Maíz", "Dulce", "Zea mays", "Poaceae", 90, "Oct-Dic", "Ene-Mar"),
    ("Brócoli", None, "Brassica oleracea var. italica", "Brassicaceae", 90, "Feb-Abr", "May-Sep"),
    ("Coliflor", None, "Brassica oleracea var. botrytis", "Brassicaceae", 110, "Ene-Mar", "May-Sep"),
    ("Repollo", None, "Brassica oleracea var. capitata", "Brassicaceae", 110, "Feb-Abr / Ago-Sep", "Todo el año"),
    ("Rabanito", None, "Raphanus sativus", "Brassicaceae", 30, "Todo el año", "Todo el año"),
    ("Frutilla", None, "Fragaria x ananassa", "Rosaceae", 180, "Mar-May", "Sep-Dic"),
]


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE SCHEMA IF NOT EXISTS adk")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_table('weather_forecasts',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=4), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('precipitation_accum', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('tmin', sa.Float(), nullable=True),
    sa.Column('tmax', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'latitude', 'longitude', 'source', 'resolution', name=op.f('pk_weather_forecasts'))
    )
    op.create_table('weather_observations',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('time', 'latitude', 'longitude', 'source', name=op.f('pk_weather_observations'))
    )
    op.create_table('crop_masters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('variety', sa.String(length=255), nullable=True),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('family', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('growth_period_days', sa.Integer(), nullable=True),
    sa.Column('planting_season', sa.String(length=255), nullable=True),
    sa.Column('harvest_season', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_crop_masters_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_masters'))
    )
    op.create_index('ix_crop_masters_account_name', 'crop_masters', ['account_id', 'name'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('soil_type', sa.String(length=100), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_fields_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields')),
    sa.UniqueConstraint('account_id', 'name', name='uq_fields_account_name')
    )
    op.create_index(op.f('ix_fields_account_id'), 'fields', ['account_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_enrolled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'tecnico', 'staff')", name=op.f('ck_users_role_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_users_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("severity IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_alerts_severity_valid')),
    sa.CheckConstraint("source IN ('rule', 'smn', 'agent', 'user')", name=op.f('ck_alerts_source_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_alerts_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_alerts_field_id_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_alerts_dedupe_key'))
    )
    op.create_index('ix_alerts_account_active', 'alerts', ['account_id', 'acknowledged_at', 'created_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_conversations_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_conversations_field_id_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_master_id', sa.UUID(), nullable=False),
    sa.Column('planting_date', sa.Date(), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('actual_harvest_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'planted', 'growing', 'harvested', 'failed')", name=op.f('ck_crop_cycles_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_crop_cycles_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_crop_cycles_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_master_id'], ['crop_masters.id'], name=op.f('fk_crop_cycles_crop_master_id_crop_masters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_crop_cycles_field_id_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crop_cycles'))
    )
    op.create_index('ix_crop_cycles_account_status', 'crop_cycles', ['account_id', 'status'], unique=False)
    op.create_index(op.f('ix_crop_cycles_field_id'), 'crop_cycles', ['field_id'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('api_key_ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_last4', sa.String(length=4), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_provider_credentials_user_provider')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('form', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('experience', sa.String(length=50), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('risk', sa.String(length=50), nullable=True),
    sa.Column('philosophy', sa.String(length=50), nullable=True),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('agent_memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', content)", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_agent_memories_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_memories_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_agent_memories_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_memories'))
    )
    op.create_index('ix_agent_memories_account_created', 'agent_memories', ['account_id', 'created_at'], unique=False)
    op.create_index('ix_agent_memories_embedding', 'agent_memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_agent_memories_tsv', 'agent_memories', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_identifier', sa.String(length=255), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_conversation_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages'))
    )
    op.create_index('ix_conversation_messages_conversation_created', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('field_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=True),
    sa.Column('author_user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_identifier', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('user', 'agent')", name=op.f('ck_field_events_source_valid')),
    sa.CheckConstraint("type IN ('sowing', 'transplant', 'irrigation', 'fertilization', 'treatment', 'pruning', 'weeding', 'pest_sighting', 'disease_sighting', 'harvest', 'observation', 'photo')", name=op.f('ck_field_events_type_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_field_events_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_field_events_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], name=op.f('fk_field_events_crop_cycle_id_crop_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_field_events_field_id_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_field_events'))
    )
    op.create_index('ix_field_events_account_occurred', 'field_events', ['account_id', 'occurred_at'], unique=False)
    op.create_index('ix_field_events_field_occurred', 'field_events', ['field_id', 'occurred_at'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('image_identifier', sa.String(length=255), nullable=True),
    sa.Column('raw_analysis_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_reports_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], name=op.f('fk_reports_crop_cycle_id_crop_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_reports_field_id_fields'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index('ix_reports_account_created', 'reports', ['account_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # TimescaleDB hypertables and retention.
    op.execute("SELECT create_hypertable('weather_observations', by_range('time', INTERVAL '7 days'))")
    op.execute("SELECT create_hypertable('weather_forecasts', by_range('time', INTERVAL '7 days'))")
    op.execute("SELECT add_retention_policy('weather_observations', INTERVAL '2 years')")
    op.execute("SELECT add_retention_policy('weather_forecasts', INTERVAL '60 days')")
    op.create_index('ix_weather_forecasts_point_time', 'weather_forecasts', ['latitude', 'longitude', 'time'])
    op.create_index('ix_weather_observations_point_time', 'weather_observations', ['latitude', 'longitude', 'time'])

    now = datetime.now(timezone.utc)
    crop_masters = sa.table(
        'crop_masters',
        sa.column('id', sa.UUID()), sa.column('account_id', sa.UUID()), sa.column('name', sa.String()),
        sa.column('variety', sa.String()), sa.column('scientific_name', sa.String()), sa.column('family', sa.String()),
        sa.column('growth_period_days', sa.Integer()), sa.column('planting_season', sa.String()),
        sa.column('harvest_season', sa.String()), sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True)),
    )
    op.bulk_insert(crop_masters, [
        {
            'id': uuid.uuid4(), 'account_id': None, 'name': name, 'variety': variety,
            'scientific_name': scientific, 'family': family, 'growth_period_days': days,
            'planting_season': planting, 'harvest_season': harvest, 'created_at': now, 'updated_at': now,
        }
        for name, variety, scientific, family, days, planting, harvest in GLOBAL_CROPS
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reports_account_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_field_events_field_occurred', table_name='field_events')
    op.drop_index('ix_field_events_account_occurred', table_name='field_events')
    op.drop_table('field_events')
    op.drop_index('ix_conversation_messages_conversation_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_agent_memories_tsv', table_name='agent_memories', postgresql_using='gin')
    op.drop_index('ix_agent_memories_embedding', table_name='agent_memories', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_agent_memories_account_created', table_name='agent_memories')
    op.drop_table('agent_memories')
    op.drop_table('user_profiles')
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_crop_cycles_field_id'), table_name='crop_cycles')
    op.drop_index('ix_crop_cycles_account_status', table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_alerts_account_active', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fields_account_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index('ix_crop_masters_account_name', table_name='crop_masters')
    op.drop_table('crop_masters')
    op.drop_index('ix_weather_observations_point_time', table_name='weather_observations')
    op.drop_index('ix_weather_forecasts_point_time', table_name='weather_forecasts')
    op.drop_table('weather_observations')
    op.drop_table('weather_forecasts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS adk CASCADE")
