"""soft delete for fields and crop cycles

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 15:32:20.641838
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop_cycles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fields', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('uq_fields_account_name'), 'fields', type_='unique')
    op.create_index('uq_fields_account_name_active', 'fields', ['account_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_fields_account_name_active', table_name='fields', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_fields_account_name'), 'fields', ['account_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('fields', 'deleted_at')
    op.drop_column('crop_cycles', 'deleted_at')
    # ### end Alembic commands ###
