"""add attachments column to conversation messages

Revision ID: 4686d205a3d6
Revises: 8c18ff0b5c97
Create Date: 2026-09-28 11:18:34.363768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '4686d205a3d6'
down_revision: Union[str, None] = '8c18ff0b5c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'conversation_messages',
        sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    )
    op.alter_column('conversation_messages', 'attachments', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'attachments')
    # ### end Alembic commands ###
