"""espacio ambiente, kc, irrigation, inventory, management, satellite

Revision ID: 8c18ff0b5c97
Revises: 0004
Create Date: 2026-09-28 11:11:12.824223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision: str = '8c18ff0b5c97'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pendiente', 'en_curso', 'hecho')", name=op.f('ck_roadmap_items_roadmap_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_roadmap_items_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_roadmap_items_field_id_fields'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roadmap_items'))
    )
    op.create_index('ix_roadmap_items_account_status', 'roadmap_items', ['account_id', 'status'], unique=False)
    op.create_table('seed_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('crop_master_id', sa.UUID(), nullable=False),
    sa.Column('variety_note', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_seed_lots_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_master_id'], ['crop_masters.id'], name=op.f('fk_seed_lots_crop_master_id_crop_masters'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seed_lots'))
    )
    op.create_index('ix_seed_lots_account', 'seed_lots', ['account_id', 'deleted_at'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pendiente', 'comprado')", name=op.f('ck_shopping_list_items_shopping_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_shopping_list_items_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_shopping_list_items_field_id_fields'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_list_items'))
    )
    op.create_index('ix_shopping_list_account_status', 'shopping_list_items', ['account_id', 'status'], unique=False)
    op.create_table('zone_satellite_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ndvi_mean', sa.Float(), nullable=True),
    sa.Column('ndvi_min', sa.Float(), nullable=True),
    sa.Column('ndvi_max', sa.Float(), nullable=True),
    sa.Column('ndwi_mean', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('image_identifier', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_zone_satellite_readings_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_zone_satellite_readings_field_id_fields'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_satellite_readings'))
    )
    op.create_index('ix_zone_satellite_readings_field_time', 'zone_satellite_readings', ['field_id', 'captured_at'], unique=False)
    op.create_table('budget_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=True),
    sa.Column('crop_cycle_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('gasto', 'ingreso')", name=op.f('ck_budget_entries_budget_type_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_budget_entries_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['crop_cycle_id'], ['crop_cycles.id'], name=op.f('fk_budget_entries_crop_cycle_id_crop_cycles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_budget_entries_field_id_fields'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_entries'))
    )
    op.create_index('ix_budget_entries_account_date', 'budget_entries', ['account_id', 'date'], unique=False)
    op.add_column('crop_masters', sa.Column('kc_initial', sa.Float(), nullable=True))
    op.add_column('crop_masters', sa.Column('kc_mid', sa.Float(), nullable=True))
    op.add_column('crop_masters', sa.Column('kc_late', sa.Float(), nullable=True))
    op.add_column('fields', sa.Column('orientation_degrees', sa.Float(), nullable=True))
    op.add_column('fields', sa.Column('length_m', sa.Float(), nullable=True))
    op.add_column('fields', sa.Column('width_m', sa.Float(), nullable=True))
    op.add_column('fields', sa.Column('obstacles', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('weather_forecasts', sa.Column('radiation', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate doesn't diff CHECK constraint bodies, so these are added by hand.
    op.drop_constraint(op.f('ck_alerts_source_valid'), 'alerts', type_='check')
    op.create_check_constraint(
        'source_valid', 'alerts', "source IN ('rule', 'smn', 'agent', 'user', 'irrigation', 'satellite')"
    )
    # reports/notifications constraints were created double-prefixed by earlier migrations
    # (op.create_check_constraint re-applies the naming convention to an already-formatted name); renamed
    # to a clean single-prefixed name here instead of perpetuating that.
    op.drop_constraint(op.f('ck_reports_ck_reports_report_type'), 'reports', type_='check')
    op.create_check_constraint(
        'report_type_valid', 'reports', "report_type IN ('diagnosis', 'periodic', 'soil')"
    )
    op.drop_constraint(op.f('ck_notifications_notification_type_valid'), 'notifications', type_='check')
    op.create_check_constraint(
        'notification_type_valid', 'notifications',
        "type IN ('report_diagnosis', 'report_periodic', 'report_soil', 'event')",
    )


def downgrade() -> None:
    op.drop_constraint(op.f('ck_notifications_notification_type_valid'), 'notifications', type_='check')
    op.create_check_constraint(
        'notification_type_valid', 'notifications',
        "type IN ('report_diagnosis', 'report_periodic', 'event')",
    )
    op.drop_constraint(op.f('ck_reports_report_type_valid'), 'reports', type_='check')
    op.create_check_constraint(
        'ck_reports_report_type', 'reports', "report_type IN ('diagnosis', 'periodic')"
    )
    op.drop_constraint(op.f('ck_alerts_source_valid'), 'alerts', type_='check')
    op.create_check_constraint('source_valid', 'alerts', "source IN ('rule', 'smn', 'agent', 'user')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_forecasts', 'radiation')
    op.drop_column('fields', 'obstacles')
    op.drop_column('fields', 'width_m')
    op.drop_column('fields', 'length_m')
    op.drop_column('fields', 'orientation_degrees')
    op.drop_column('crop_masters', 'kc_late')
    op.drop_column('crop_masters', 'kc_mid')
    op.drop_column('crop_masters', 'kc_initial')
    op.drop_index('ix_budget_entries_account_date', table_name='budget_entries')
    op.drop_table('budget_entries')
    op.drop_index('ix_zone_satellite_readings_field_time', table_name='zone_satellite_readings')
    op.drop_table('zone_satellite_readings')
    op.drop_index('ix_shopping_list_account_status', table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index('ix_seed_lots_account', table_name='seed_lots')
    op.drop_table('seed_lots')
    op.drop_index('ix_roadmap_items_account_status', table_name='roadmap_items')
    op.drop_table('roadmap_items')
    # ### end Alembic commands ###
