from datetime import date, datetime
from typing import Any, Dict, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field as PField, field_validator, model_validator

from src.application.soil_data.schemas import SoilContext

Octant = Literal["N", "NE", "E", "SE", "S", "SO", "O", "NO"]
CropCycleStatus = Literal["planned", "planted", "growing", "harvested", "failed"]
EventType = Literal[
    "sowing",
    "transplant",
    "irrigation",
    "fertilization",
    "treatment",
    "pruning",
    "weeding",
    "pest_sighting",
    "disease_sighting",
    "harvest",
    "observation",
    "photo",
]


class ORMModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)


# ---------- Fields ----------

LayoutObjectType = Literal["pared", "cerco", "arbol", "estructura", "pileta", "cantero", "terreno", "otro"]
LayoutKind = Literal["polygon", "polyline", "circle"]


class LayoutObject(BaseModel):
    """One element of the field's top-down plan (a wall, a tree, the pool, the terrain outline...), in real
    meters on a local frame centered on the field: x = East (+), y = North (+), no fixed extent.

    Geometry depends on `kind`: `polygon` (closed shape) and `polyline` (open line drawn with `thickness_m`,
    e.g. a wall or hedge) carry `points`; `circle` (a tree crown) uses x_m/y_m as center plus `radius_m`.
    Objects saved before shapes existed are plain points and read as small circles."""

    id: str  # uuid4 hex, generated by whoever creates it (client or photo extraction)
    type: LayoutObjectType
    label: str
    kind: LayoutKind = "circle"
    x_m: float = PField(default=0.0, description="Meters East (+)/West (-); circle center, or centroid of points")
    y_m: float = PField(default=0.0, description="Meters North (+)/South (-); circle center, or centroid of points")
    radius_m: Optional[float] = PField(default=None, gt=0, le=100)
    points: Optional[list[tuple[float, float]]] = PField(default=None, description="Vertices as (x_m, y_m)")
    thickness_m: Optional[float] = PField(default=None, gt=0, le=50, description="Line width for polylines")
    height_m: float = PField(default=0.0, ge=0, le=100)
    source: Literal["photo_ai", "manual"] = "manual"
    confidence: Optional[float] = PField(default=None, ge=0, le=1)
    photo_id: Optional[str] = PField(default=None, description="Reference photo this element was detected in")

    @model_validator(mode="after")
    def _check_geometry(self):
        if self.kind == "circle":
            return self
        minimum = 3 if self.kind == "polygon" else 2
        if not self.points or len(self.points) < minimum:
            raise ValueError(f"A {self.kind} needs at least {minimum} points.")
        self.x_m = sum(p[0] for p in self.points) / len(self.points)
        self.y_m = sum(p[1] for p in self.points) / len(self.points)
        return self


class LayoutPhoto(BaseModel):
    """A reference photo used to build the layout, kept so the plan can show where it was taken from."""

    id: str
    image_identifier: str
    camera_bearing_degrees: float = PField(ge=0, le=360, description="TRUE-north direction the camera faced")
    reference_note: Optional[str] = PField(default=None, description="The user's own distance/height note")
    camera_x_m: Optional[float] = PField(default=None, description="Where the photo was taken, on the plan (East +)")
    camera_y_m: Optional[float] = PField(default=None, description="Where the photo was taken, on the plan (North +)")
    pitch_degrees: Optional[float] = PField(default=None, ge=-90, le=90, description="Phone tilt (+ = looking up)")
    camera_height_m: Optional[float] = PField(default=None, gt=0, le=20, description="Camera height above ground")
    # The photo is processed in the background (like a diagnosis report): the upload returns immediately as
    # "processing"; the detected objects are merged into the field's layout when it finishes.
    status: Literal["processing", "done", "failed"] = "done"
    error: Optional[str] = None
    updated_at: Optional[str] = PField(default=None, description="ISO timestamp of the last status change")


def _check_boundary(v: Optional[list[tuple[float, float]]]) -> Optional[list[tuple[float, float]]]:
    if v is not None and 0 < len(v) < 3:
        raise ValueError("A boundary needs at least 3 points to form a shape.")
    return v


class FieldBase(BaseModel):
    name: str = PField(min_length=1, max_length=255)
    city: Optional[str] = None
    latitude: Optional[float] = PField(default=None, ge=-90, le=90)
    longitude: Optional[float] = PField(default=None, ge=-180, le=180)
    boundary: Optional[list[tuple[float, float]]] = PField(
        default=None, description="The field's own drawn boundary as (lat, lon) points — not the ~500m zone box"
    )
    description: Optional[str] = None
    soil_type: Optional[str] = None
    area_m2: Optional[float] = PField(default=None, ge=0)
    length_m: Optional[float] = PField(default=None, ge=0)
    width_m: Optional[float] = PField(default=None, ge=0)
    layout_objects: list[LayoutObject] = PField(default_factory=list)
    layout_photos: list[LayoutPhoto] = PField(default_factory=list)

    _check_boundary = field_validator("boundary")(_check_boundary)


class FieldCreate(FieldBase):
    pass


class FieldUpdate(BaseModel):
    name: Optional[str] = PField(default=None, min_length=1, max_length=255)
    city: Optional[str] = None
    latitude: Optional[float] = PField(default=None, ge=-90, le=90)
    longitude: Optional[float] = PField(default=None, ge=-180, le=180)
    boundary: Optional[list[tuple[float, float]]] = None
    description: Optional[str] = None
    soil_type: Optional[str] = None
    area_m2: Optional[float] = PField(default=None, ge=0)
    length_m: Optional[float] = PField(default=None, ge=0)
    width_m: Optional[float] = PField(default=None, ge=0)
    layout_objects: Optional[list[LayoutObject]] = None
    layout_photos: Optional[list[LayoutPhoto]] = None

    _check_boundary = field_validator("boundary")(_check_boundary)


class FieldRead(FieldBase, ORMModel):
    id: UUID
    account_id: UUID
    soil_context: Optional[SoilContext] = None
    created_at: datetime
    updated_at: datetime


class SunExposureRead(BaseModel):
    field_id: UUID
    field_name: str
    by_season: Dict[str, Dict[str, float]]  # season -> octant -> hours of direct sun


# ---------- Crop masters ----------

class CropMasterBase(BaseModel):
    name: str = PField(min_length=1, max_length=255)
    variety: Optional[str] = None
    scientific_name: Optional[str] = None
    family: Optional[str] = None
    description: Optional[str] = None
    growth_period_days: Optional[int] = PField(default=None, ge=1, le=3650)
    planting_season: Optional[str] = None
    harvest_season: Optional[str] = None
    kc_initial: Optional[float] = PField(default=None, ge=0, le=2, description="FAO-56 Kc, initial stage")
    kc_mid: Optional[float] = PField(default=None, ge=0, le=2, description="FAO-56 Kc, mid-season stage")
    kc_late: Optional[float] = PField(default=None, ge=0, le=2, description="FAO-56 Kc, late-season stage")


class CropMasterCreate(CropMasterBase):
    pass


class CropMasterRead(CropMasterBase, ORMModel):
    id: UUID
    account_id: Optional[UUID] = None
    created_at: datetime
    updated_at: datetime

    @property
    def is_global(self) -> bool:
        return self.account_id is None


# ---------- Crop cycles ----------

class CropCycleCreate(BaseModel):
    field_id: UUID
    crop_master_id: UUID
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None
    actual_harvest_date: Optional[date] = None
    status: CropCycleStatus = "planned"
    notes: Optional[str] = None


class CropCycleUpdate(BaseModel):
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None
    actual_harvest_date: Optional[date] = None
    status: Optional[CropCycleStatus] = None
    notes: Optional[str] = None


class CropCycleRead(ORMModel):
    id: UUID
    account_id: UUID
    field_id: UUID
    crop_master_id: UUID
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None
    actual_harvest_date: Optional[date] = None
    status: CropCycleStatus
    notes: Optional[str] = None
    created_by: Optional[UUID] = None
    created_at: datetime
    updated_at: datetime


# ---------- Field events ----------

class FieldEventCreate(BaseModel):
    field_id: UUID
    crop_cycle_id: Optional[UUID] = None
    type: EventType
    occurred_at: Optional[datetime] = None
    quantity: Optional[float] = None
    unit: Optional[str] = PField(default=None, max_length=30)
    notes: Optional[str] = None
    data: Dict[str, Any] = PField(default_factory=dict)
    image_identifier: Optional[str] = None


class FieldEventUpdate(BaseModel):
    type: Optional[EventType] = None
    occurred_at: Optional[datetime] = None
    quantity: Optional[float] = None
    unit: Optional[str] = PField(default=None, max_length=30)
    notes: Optional[str] = None
    data: Optional[Dict[str, Any]] = None


class FieldEventRead(ORMModel):
    id: UUID
    account_id: UUID
    field_id: UUID
    crop_cycle_id: Optional[UUID] = None
    author_user_id: Optional[UUID] = None
    type: EventType
    occurred_at: datetime
    quantity: Optional[float] = None
    unit: Optional[str] = None
    notes: Optional[str] = None
    data: Dict[str, Any] = PField(default_factory=dict)
    image_identifier: Optional[str] = None
    source: Literal["user", "agent"]
    created_at: datetime


# ---------- Overview (used by the agent) ----------

class ActiveCycleSummary(BaseModel):
    id: UUID
    crop_name: str
    variety: Optional[str] = None
    status: CropCycleStatus
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None


class FieldOverview(BaseModel):
    field: FieldRead
    active_cycles: list[ActiveCycleSummary]
    last_event_at: Optional[datetime] = None
