from datetime import date, datetime
from typing import Any, Dict, Literal, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field as PField, field_validator

from src.application.soil_data.schemas import SoilContext

Octant = Literal["N", "NE", "E", "SE", "S", "SO", "O", "NO"]
CropCycleStatus = Literal["planned", "planted", "growing", "harvested", "failed"]
EventType = Literal[
    "sowing",
    "transplant",
    "irrigation",
    "fertilization",
    "treatment",
    "pruning",
    "weeding",
    "pest_sighting",
    "disease_sighting",
    "harvest",
    "observation",
    "photo",
]


class ORMModel(BaseModel):
    model_config = ConfigDict(from_attributes=True)


# ---------- Fields ----------

class LayoutObject(BaseModel):
    """One thing around the plot that affects its sun/shade (a wall, a tree...), placed on a top-down plan
    whose origin is the field's center and whose axes are real compass axes (x=East+, y=North+)."""

    id: str  # uuid4 hex, generated by whoever creates it (client or photo extraction)
    type: Literal["pared", "arbol", "estructura", "pileta", "cantero", "otro"]
    label: str
    x_m: float = PField(description="Meters East (+) / West (-) of the field's center")
    y_m: float = PField(description="Meters North (+) / South (-) of the field's center")
    height_m: float = PField(ge=0, le=100)
    source: Literal["photo_ai", "manual"]
    confidence: Optional[float] = PField(default=None, ge=0, le=1)


class LayoutPhoto(BaseModel):
    """A reference photo used to build the layout, kept so the plan can show where it was taken from."""

    id: str
    image_identifier: str
    camera_bearing_degrees: float = PField(ge=0, le=360, description="TRUE-north direction the camera faced")
    reference_note: Optional[str] = PField(default=None, description="The user's own distance/height note")


def _check_boundary(v: Optional[list[tuple[float, float]]]) -> Optional[list[tuple[float, float]]]:
    if v is not None and 0 < len(v) < 3:
        raise ValueError("A boundary needs at least 3 points to form a shape.")
    return v


class FieldBase(BaseModel):
    name: str = PField(min_length=1, max_length=255)
    city: Optional[str] = None
    latitude: Optional[float] = PField(default=None, ge=-90, le=90)
    longitude: Optional[float] = PField(default=None, ge=-180, le=180)
    boundary: Optional[list[tuple[float, float]]] = PField(
        default=None, description="The field's own drawn boundary as (lat, lon) points — not the ~500m zone box"
    )
    description: Optional[str] = None
    soil_type: Optional[str] = None
    area_m2: Optional[float] = PField(default=None, ge=0)
    length_m: Optional[float] = PField(default=None, ge=0)
    width_m: Optional[float] = PField(default=None, ge=0)
    layout_objects: list[LayoutObject] = PField(default_factory=list)
    layout_photos: list[LayoutPhoto] = PField(default_factory=list)

    _check_boundary = field_validator("boundary")(_check_boundary)


class FieldCreate(FieldBase):
    pass


class FieldUpdate(BaseModel):
    name: Optional[str] = PField(default=None, min_length=1, max_length=255)
    city: Optional[str] = None
    latitude: Optional[float] = PField(default=None, ge=-90, le=90)
    longitude: Optional[float] = PField(default=None, ge=-180, le=180)
    boundary: Optional[list[tuple[float, float]]] = None
    description: Optional[str] = None
    soil_type: Optional[str] = None
    area_m2: Optional[float] = PField(default=None, ge=0)
    length_m: Optional[float] = PField(default=None, ge=0)
    width_m: Optional[float] = PField(default=None, ge=0)
    layout_objects: Optional[list[LayoutObject]] = None
    layout_photos: Optional[list[LayoutPhoto]] = None

    _check_boundary = field_validator("boundary")(_check_boundary)


class FieldRead(FieldBase, ORMModel):
    id: UUID
    account_id: UUID
    soil_context: Optional[SoilContext] = None
    created_at: datetime
    updated_at: datetime


class SunExposureRead(BaseModel):
    field_id: UUID
    field_name: str
    by_season: Dict[str, Dict[str, float]]  # season -> octant -> hours of direct sun


# ---------- Crop masters ----------

class CropMasterBase(BaseModel):
    name: str = PField(min_length=1, max_length=255)
    variety: Optional[str] = None
    scientific_name: Optional[str] = None
    family: Optional[str] = None
    description: Optional[str] = None
    growth_period_days: Optional[int] = PField(default=None, ge=1, le=3650)
    planting_season: Optional[str] = None
    harvest_season: Optional[str] = None
    kc_initial: Optional[float] = PField(default=None, ge=0, le=2, description="FAO-56 Kc, initial stage")
    kc_mid: Optional[float] = PField(default=None, ge=0, le=2, description="FAO-56 Kc, mid-season stage")
    kc_late: Optional[float] = PField(default=None, ge=0, le=2, description="FAO-56 Kc, late-season stage")


class CropMasterCreate(CropMasterBase):
    pass


class CropMasterRead(CropMasterBase, ORMModel):
    id: UUID
    account_id: Optional[UUID] = None
    created_at: datetime
    updated_at: datetime

    @property
    def is_global(self) -> bool:
        return self.account_id is None


# ---------- Crop cycles ----------

class CropCycleCreate(BaseModel):
    field_id: UUID
    crop_master_id: UUID
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None
    actual_harvest_date: Optional[date] = None
    status: CropCycleStatus = "planned"
    notes: Optional[str] = None


class CropCycleUpdate(BaseModel):
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None
    actual_harvest_date: Optional[date] = None
    status: Optional[CropCycleStatus] = None
    notes: Optional[str] = None


class CropCycleRead(ORMModel):
    id: UUID
    account_id: UUID
    field_id: UUID
    crop_master_id: UUID
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None
    actual_harvest_date: Optional[date] = None
    status: CropCycleStatus
    notes: Optional[str] = None
    created_by: Optional[UUID] = None
    created_at: datetime
    updated_at: datetime


# ---------- Field events ----------

class FieldEventCreate(BaseModel):
    field_id: UUID
    crop_cycle_id: Optional[UUID] = None
    type: EventType
    occurred_at: Optional[datetime] = None
    quantity: Optional[float] = None
    unit: Optional[str] = PField(default=None, max_length=30)
    notes: Optional[str] = None
    data: Dict[str, Any] = PField(default_factory=dict)
    image_identifier: Optional[str] = None


class FieldEventUpdate(BaseModel):
    type: Optional[EventType] = None
    occurred_at: Optional[datetime] = None
    quantity: Optional[float] = None
    unit: Optional[str] = PField(default=None, max_length=30)
    notes: Optional[str] = None
    data: Optional[Dict[str, Any]] = None


class FieldEventRead(ORMModel):
    id: UUID
    account_id: UUID
    field_id: UUID
    crop_cycle_id: Optional[UUID] = None
    author_user_id: Optional[UUID] = None
    type: EventType
    occurred_at: datetime
    quantity: Optional[float] = None
    unit: Optional[str] = None
    notes: Optional[str] = None
    data: Dict[str, Any] = PField(default_factory=dict)
    image_identifier: Optional[str] = None
    source: Literal["user", "agent"]
    created_at: datetime


# ---------- Overview (used by the agent) ----------

class ActiveCycleSummary(BaseModel):
    id: UUID
    crop_name: str
    variety: Optional[str] = None
    status: CropCycleStatus
    planting_date: Optional[date] = None
    expected_harvest_date: Optional[date] = None


class FieldOverview(BaseModel):
    field: FieldRead
    active_cycles: list[ActiveCycleSummary]
    last_event_at: Optional[datetime] = None
